sudo: required
servises:
  - docker

before_install:
  - docker build -t mojtabayazdankhah79/my-first-web -f Dockerfile.dev .

script:
  - docker run mojtabayazdankhah79/my-first-web npm run test -- --coverage
